import jinja2 as j2

CLASSES = [
    "Area",
    "Arrow",
    "BarX",
    "BarY",
    "Cell",
    "Dot",
    "Frame",
    "Image",
    "Line",
    "Link",
    "Mark",
    "Rect",
    "RuleX",
    "RuleY",
    "Text",
    "TickX",
    "TickY",
    "Vector",
]

template = j2.Template(
    """
# AUTOGENERATED - See scripts/generate_class_wrappers.py
from .plottable import Plottable

class {{ class_name }}(Plottable):
    def __init__(self, data, **kwargs):
        super().__init__(data, **kwargs)
"""
)


def main():
    for cls in CLASSES:
        text = template.render(class_name=cls)
        with open("duboce/marks/" + cls.lower() + ".py", "w+") as f:
            f.write(text)


if __name__ == "__main__":
    main()
